spring.application.name=sprint-boot-tutorial
spring.datasource.url=jdbc:postgresql://localhost:5332/postgres_db
spring.datasource.username=amigoscode
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

